### PR TITLE
Clarify the HOF

### PR DESCRIPTION
**Pull request by weblancaster**
I think things must be as simple as possible for any person to understand.. one of the problems we have in the dev community is to be learning "friendly".

### CODE REVIEW

**Comment by jasonbellamy** [comment]
I personally think the original description was easier to understand and more clearly describes higher order functions.

**Comment by davidchambers** [comment]
See also #9

**Comment by CrossEye** [comment]
I had started my own PR on this before leaving for some errands.  Both the original and this one have real problems with accuracy.  The definition from #9 is still simple but also accurate.

I'd still like to see simpler examples, probably several of them, one for a a function that accepts a function as input, one for one that returns a function, and one for a function that does both.  But I would vote for the definition from #9.

**Comment by hemanth** [comment]
#9 is merged, thanks @weblancaster

**Pull request closed without merging**
